development: &defaults
  :twitter:
    :app_id: ""
    :app_secret: ""
  :facebook:
    :app_id: ""
    :app_secret: ""
    :options:
      :scope: "publish_stream,read_stream"
  :linked_in:
    :app_id: ""
    :app_secret: ""
  :google:
    :app_id: ""
    :app_secret: "N-"
    :options:
      :scope: 'https://docs.google.com/feeds/ https://spreadsheets.google.com/feeds/' # http://code.google.com/apis/gdata/faq.html#AuthScopes

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

